'use client';

import {useEffect,useRef,useState} from 'react';
import {Check,CheckCheck,ChevronDown,Download,FileImage,Files,Info,LoaderCircle,RotateCw,ShieldCheck,Upload,X,AlertTriangle,Eye,ClipboardList} from 'lucide-react';
import {SAMPLE,WARNING,verify,csvCell} from '../lib/verify.mjs';
import {recognize,warmEngine} from '../lib/ocr';

type Application=typeof SAMPLE;
type Result=ReturnType<typeof verify>;
type Item={id:string;name:string;url:string;blob:Blob;rotation:number;app:Application;text?:string;confidence?:number;seconds?:number;result?:Result;error?:string;state:'queued'|'reading'|'done'|'error';decision?:string;notes?:string};
const fields=[['brand','Brand name','e.g. OLD TOM DISTILLERY'],['type','Class / type','e.g. Kentucky Straight Bourbon Whiskey'],['abv','Alcohol content (% ABV)','e.g. 45'],['net','Net contents','e.g. 750 mL'],['producer','Producer / bottler and address','As written in the application'],['origin','Country of origin','Required for imports']] as const;
const empty:Application={brand:'',type:'',abv:'',net:'',producer:'',origin:'',beverage:'spirits',imported:false,abvRequired:true};
const source='https://www.ttb.gov/regulated-commodities/beverage-alcohol/distilled-spirits/ds-labeling-home/ds-health-warning';

function download(name:string,content:string,type='text/plain'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Pill({status}:{status:string}){const title=status==='match'?'Match':status==='mismatch'?'Mismatch':status==='skip'?'Not required':'Review';return <span className={`pill ${status}`}>{status==='match'?<Check size={13}/>:status==='mismatch'?<X size={13}/>:status==='skip'?null:<Eye size={13}/>} {title}</span>;}

export default function Home(){
 const [mode,setMode]=useState<'single'|'batch'>('single'),[app,setApp]=useState<Application>(empty),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[engine,setEngine]=useState('Starting local reader…'),[message,setMessage]=useState(''),[drag,setDrag]=useState(false),[filter,setFilter]=useState('all'),[zoom,setZoom]=useState(false),[manifest,setManifest]=useState<Record<string,Application>>({}),[guide,setGuide]=useState(false);
 const uploadRef=useRef<HTMLInputElement>(null),manifestRef=useRef<HTMLInputElement>(null),itemsRef=useRef<Item[]>([]),stop=useRef(false);
 const current=items.find(x=>x.id===selected),currentRef=useRef<Item|undefined>(current);currentRef.current=current;itemsRef.current=items;
 useEffect(()=>{let alive=true;warmEngine().then(()=>{if(alive)setEngine('Local reader ready');}).catch(()=>{if(alive)setEngine('Reader will retry when you verify');});return()=>{alive=false;itemsRef.current.forEach(x=>URL.revokeObjectURL(x.url));};},[]);
 useEffect(()=>{if(!zoom&&!guide)return;const previous=document.activeElement as HTMLElement|null;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setZoom(false);setGuide(false);}if(e.key==='Tab'){const elements=Array.from(document.querySelectorAll<HTMLElement>('.modal button,.modal a[href]'));const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[zoom,guide]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();void Promise.resolve(context.registerTool({name:'read_label_review',description:'Read the currently selected label comparison and reviewer decision.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const x=currentRef.current;return x?{name:x.name,state:x.state,result:x.result,decision:x.decision||null}: {state:'empty'};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 function update(id:string,patch:Partial<Item>){setItems(prev=>prev.map(x=>x.id===id?{...x,...patch}:x));}
 function changeApp(next:Application){setApp(next);if(current)update(current.id,{app:next,result:current.text!==undefined?verify(current.text,next,current.confidence):undefined,decision:undefined});}
 function select(x:Item){setSelected(x.id);setApp(x.app);}
 function addFiles(files:File[]){
  setMessage('');const valid=files.filter(f=>['image/png','image/jpeg','image/webp'].includes(f.type)&&f.size<=12*1024*1024);
  if(valid.length!==files.length)setMessage('Some files were skipped. Use PNG, JPG or WebP images up to 12 MB each.');
  const room=300-items.length;if(valid.length>room)setMessage('The queue holds up to 300 labels. Clear it before adding more.');
  const added=valid.slice(0,Math.max(0,room)).map(f=>({id:crypto.randomUUID(),name:f.name,blob:f,url:URL.createObjectURL(f),rotation:0,app:{...(manifest[f.name]||app)},state:'queued' as const}));
  if(!added.length)return;setItems(prev=>[...prev,...added]);select(added[0]);if(added.length>1)setMode('batch');
 }
 async function loadSample(kind:string){if(busy)return;setMessage('');try{const name=`old-tom-${kind}.png`;const res=await fetch(`/samples/${name}`);if(!res.ok)throw new Error('Sample could not be loaded.');const blob=await res.blob();const item:Item={id:crypto.randomUUID(),name,blob,url:URL.createObjectURL(blob),rotation:0,app:{...SAMPLE},state:'queued'};if(items.length>=300)throw new Error('Clear the queue before adding another sample.');setItems(p=>[...p,item]);select(item);}catch(e){setMessage(e instanceof Error?e.message:'Could not load the sample.');}}
 async function run(batch=false){if(busy)return;const queue=batch?items.filter(x=>x.state==='queued'||x.state==='error'):current?[current]:[];if(!queue.length){setMessage('Add a label image first.');return;}setBusy(true);stop.current=false;setMessage('');try{for(const x of queue){if(stop.current)break;update(x.id,{state:'reading',error:undefined,decision:undefined});try{const read=await recognize(x.blob,x.rotation);update(x.id,{...read,result:verify(read.text,x.app,read.confidence),state:'done'});setEngine('Local reader ready');}catch(e){update(x.id,{state:'error',error:e instanceof Error?e.message:'Could not read this image. Try another file.'});}}}finally{setBusy(false);}}
 async function importManifest(file:File){try{if(file.size>1024*1024)throw new Error('Manifest must be under 1 MB.');const raw=JSON.parse(await file.text());if(!Array.isArray(raw)||raw.length>300)throw new Error('Use a JSON array with up to 300 applications.');const map:Record<string,Application>={};for(const row of raw){if(!row||typeof row!=='object'||typeof row.filename!=='string'||!row.filename.trim())throw new Error('Each application needs a filename.');if(map[row.filename])throw new Error(`Duplicate filename: ${row.filename}`);const a={...empty};for(const [key]of fields){if(row[key]!==undefined&&typeof row[key]!=='string')throw new Error(`${key} must be a string.`);a[key]=row[key]||'';}if(row.imported!==undefined&&typeof row.imported!=='boolean')throw new Error('imported must be true or false.');if(row.abvRequired!==undefined&&typeof row.abvRequired!=='boolean')throw new Error('abvRequired must be true or false.');a.imported=row.imported===true;a.abvRequired=row.abvRequired!==false;if(row.beverage&&!['spirits','wine','beer'].includes(row.beverage))throw new Error('beverage must be spirits, wine or beer.');a.beverage=row.beverage||'spirits';map[row.filename]=a;}setManifest(map);setItems(prev=>prev.map(x=>map[x.name]?{...x,app:map[x.name],result:x.text!==undefined?verify(x.text,map[x.name],x.confidence):undefined,decision:undefined}:x));if(current&&map[current.name])setApp(map[current.name]);setMessage(`Application data loaded for ${Object.keys(map).length} files. Matching is by exact filename.`);}catch(e){setMessage(e instanceof Error?e.message:'Invalid manifest.');}}
 function exportResults(){const rows=[['File','Field','Application','Recognized','Result','Detail','OCR confidence','Seconds','Reviewer decision','Notes']];for(const x of items)if(x.result)for(const r of x.result.rows)rows.push([x.name,r.field,r.expected,r.observed,r.status,r.note,String(x.confidence),x.seconds?.toFixed(2)||'',x.decision||'Pending',x.notes||'']);else if(x.error)rows.push([x.name,'Read error','','','error',x.error,'','','Pending','']);download('labelcheck-results.csv',rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv');}
 function clear(){items.forEach(x=>URL.revokeObjectURL(x.url));setItems([]);setSelected('');setApp(empty);setManifest({});setMessage('');}
 const shown=items.filter(x=>filter==='all'||filter==='queued'?filter==='all'||x.state==='queued':filter==='issues'?x.result?.status==='mismatch':x.state==='done'&&x.result?.status==='review');
 const done=items.filter(x=>x.state==='done').length,issues=items.filter(x=>x.result?.status==='mismatch').length;
 return <><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><ShieldCheck size={23}/></span>LabelCheck<span className="prototype">PROTOTYPE</span></a><div className="top-right"><span className="local"><ShieldCheck size={15}/> Images stay on this device</span><button className="quiet" onClick={()=>setGuide(true)}><Info size={17}/> Review guide</button></div></header>
 <main><div className="page-heading"><div><p className="eyebrow">LABEL COMPLIANCE WORKSPACE</p><h1>Less checking. More judgment.</h1><p className="intro">Compare label artwork with application details, one label or a whole batch.</p></div><div className="reader"><span className={engine==='Local reader ready'?'ready-dot':'loading-dot'}/>{engine}</div></div>
 <div className="workspace-bar"><div className="tabs" role="tablist" aria-label="Review mode"><button role="tab" aria-selected={mode==='single'} className={mode==='single'?'active':''} onClick={()=>setMode('single')}><FileImage size={17}/> Single label</button><button role="tab" aria-selected={mode==='batch'} className={mode==='batch'?'active':''} onClick={()=>setMode('batch')}><Files size={17}/> Batch review {items.length>0&&<span className="count">{items.length}</span>}</button></div><button className="quiet" disabled={!items.some(x=>x.result||x.error)} onClick={exportResults}><Download size={16}/> Export results</button></div>
 {message&&<div className="notice" role="status"><Info size={18}/><span>{message}</span><button aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {mode==='batch'&&<section className="batch-panel"><div className="batch-top"><div><h2>Review queue <span>{done} of {items.length} read · {issues} with mismatches</span></h2><p>Each image has its own application details. Import a manifest to fill them by filename.</p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>manifestRef.current?.click()}><ClipboardList size={16}/> Import applications</button><button className="primary" disabled={busy||!items.some(x=>x.state==='queued'||x.state==='error')} onClick={()=>void run(true)}>{busy?<LoaderCircle className="spin" size={16}/>:<CheckCheck size={16}/>} Verify queue</button>{busy&&<button className="secondary" onClick={()=>{stop.current=true;setMessage('The queue will pause after the current label.');}}>Pause queue</button>}</div></div><input ref={manifestRef} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importManifest(f);e.target.value='';}}/><div className="queue-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All labels</button><button className={filter==='issues'?'active':''} onClick={()=>setFilter('issues')}>Mismatches</button><button className={filter==='review'?'active':''} onClick={()=>setFilter('review')}>Needs review</button><button className={filter==='queued'?'active':''} onClick={()=>setFilter('queued')}>Queued</button><button className="manifest-download" onClick={()=>download('applications.json',JSON.stringify([{filename:'old-tom-match.png',...SAMPLE}],null,2),'application/json')}>Download manifest example</button></div><div className="queue-list">{shown.length?shown.map(x=><button key={x.id} className={`queue-item ${x.id===selected?'selected':''}`} disabled={busy} onClick={()=>select(x)}><FileImage size={18}/><span>{x.name}<small>{x.app.brand||'Application details needed'}</small></span><span className={`queue-status ${x.result?.status||x.state}`}>{x.state==='reading'?'Reading…':x.state==='error'?'Read failed':x.state==='queued'?'Queued':x.result?.status==='mismatch'?'Mismatch':'Needs review'}</span></button>):<p className="queue-empty">{items.length?'No labels in this view.':'Upload images below to build your queue.'}</p>}</div></section>}
 <div className="work-grid"><section className="panel application"><div className="panel-heading"><span className="step">1</span><h2>Application details</h2><span className="panel-sub">Expected values</span></div><div className="form-content"><label>Beverage category<div className="select-wrap"><select disabled={busy} value={app.beverage} onChange={e=>changeApp({...app,beverage:e.target.value})}><option value="spirits">Distilled spirits</option><option value="wine">Wine</option><option value="beer">Beer / malt beverage</option></select><ChevronDown size={15}/></div></label><div className="fields">{fields.map(([key,title,placeholder])=><label key={key} className={key==='abv'||key==='net'?'half':'full'}>{title}{key==='origin'&&!app.imported&&<span className="optional">optional</span>}<input disabled={busy} value={app[key]} placeholder={placeholder} inputMode={key==='abv'?'decimal':undefined} onChange={e=>changeApp({...app,[key]:e.target.value})}/></label>)}</div><label className="checkbox"><input type="checkbox" disabled={busy} checked={app.imported} onChange={e=>changeApp({...app,imported:e.target.checked})}/> Imported product</label><label className="checkbox"><input type="checkbox" disabled={busy} checked={app.abvRequired} onChange={e=>changeApp({...app,abvRequired:e.target.checked})}/> ABV is required for this application</label><div className="form-note"><Info size={17}/><p>Brand names ignore case and curly quotes. Numbers are compared using equivalent units.</p></div></div><div className="panel-bottom"><span>New to the workspace?</span><button disabled={busy} onClick={()=>void loadSample('match')}>Try a sample label</button></div></section>
 <section className="panel artwork"><div className="panel-heading"><span className="step">2</span><h2>Label artwork</h2><span className="panel-sub">PNG, JPG or WebP</span></div><input ref={uploadRef} type="file" multiple accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value='';}}/>
 {current?<div className="image-workspace"><div className="image-toolbar"><span><FileImage size={15}/>{current.name}</span><div><button className="quiet" disabled={busy} onClick={()=>update(current.id,{rotation:(current.rotation+90)%360,state:'queued',text:undefined,result:undefined,decision:undefined})}><RotateCw size={15}/> Rotate</button><button className="quiet" onClick={()=>setZoom(true)}><Eye size={15}/> Enlarge</button><button className="quiet" disabled={busy} onClick={()=>uploadRef.current?.click()}><Upload size={15}/> Add image</button></div></div><div className="image-stage" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)addFiles(Array.from(e.dataTransfer.files));}}><img alt={`Label artwork: ${current.name}`} src={current.url} style={{transform:`rotate(${current.rotation}deg)`}}/></div><div className="verify-bar"><p>{current.state==='reading'?'Reading the label on your device…':current.seconds!==undefined?`Read in ${current.seconds.toFixed(2)} seconds · ${Math.round(current.confidence||0)}% OCR confidence`:'Check your application details, then verify.'}</p><button className="primary" disabled={busy} onClick={()=>void run()}>{busy?<LoaderCircle className="spin" size={17}/>:<ShieldCheck size={17}/>} {current.state==='done'?'Verify again':'Verify label'}</button></div>{current.error&&<div className="error-message" role="alert"><AlertTriangle size={18}/>{current.error}</div>}</div>:<div className={`upload-area ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(Array.from(e.dataTransfer.files));}}><div className="upload-icon"><Upload size={28}/></div><h3>Drop label artwork here</h3><p>Upload a clear image of the full label.<br/>Include the panel containing the health warning.</p><button className="primary" onClick={()=>uploadRef.current?.click()}><Upload size={17}/> Choose {mode==='batch'?'images':'image'}</button><span className="upload-limit">Up to 12 MB per image · Batch queue up to 300</span></div>}
 <div className="sample-bar"><span>TEST LABELS</span><button disabled={busy} onClick={()=>void loadSample('match')}>Matching text</button><button disabled={busy} onClick={()=>void loadSample('abv')}>Wrong ABV</button><button disabled={busy} onClick={()=>void loadSample('warning')}>Warning error</button></div></section></div>
 {current?.result&&<section className="panel results" aria-live="polite"><div className={`result-banner ${current.result.status}`}><span className="result-symbol">{current.result.status==='mismatch'?<AlertTriangle size={24}/>:<Eye size={24}/>}</span><div><h2>{current.result.status==='mismatch'?'Mismatches found':'Text checked. Finish the visual review.'}</h2><p>{current.result.rows.filter(r=>r.status==='match').length} checks match · {current.result.rows.filter(r=>r.status==='mismatch').length} mismatches · {current.result.rows.filter(r=>r.status==='review').length} need review</p></div><span className="elapsed">{current.seconds?.toFixed(2)}s <small>{(current.seconds||0)<=5?'within 5s target':'above 5s target'}</small></span></div><div className="table-scroll"><table><thead><tr><th>Label field</th><th>Application / requirement</th><th>Recognized on label</th><th>Result</th></tr></thead><tbody>{current.result.rows.map(r=><tr key={r.field}><th>{r.field}</th><td>{r.field==='Warning text'?<details><summary>Standard government warning</summary><p>{r.expected}</p></details>:r.expected}</td><td><span>{r.observed}</span><small>{r.note}</small></td><td><Pill status={r.status}/></td></tr>)}</tbody></table></div><details className="recognized"><summary>View recognized text</summary><pre>{current.text||'No readable text was recognized.'}</pre></details><div className="decision"><div><h3>Reviewer decision</h3><p>Confirm formatting and label-specific requirements before recording a decision.</p></div><select aria-label="Reviewer decision" value={current.decision||''} onChange={e=>update(current.id,{decision:e.target.value})}><option value="">Select decision</option><option>Accept after visual review</option><option>Return for correction</option><option>Request clearer artwork</option></select><input aria-label="Reviewer notes" placeholder="Review notes (optional)" value={current.notes||''} onChange={e=>update(current.id,{notes:e.target.value})}/></div></section>}
 <footer><span><ShieldCheck size={15}/> Review assistance · Final decisions stay with the agent</span><div><a href={source} target="_blank" rel="noreferrer">TTB health warning guidance</a><button className="quiet" disabled={busy||!items.length} onClick={clear}>Clear workspace</button></div></footer></main>
 {(zoom||guide)&&<div className="modal-backdrop" onClick={()=>{setZoom(false);setGuide(false);}}><section role="dialog" aria-modal="true" aria-label={zoom?'Enlarged label':'Review guide'} className={`modal ${zoom?'image-modal':''}`}><button autoFocus className="modal-close" aria-label="Close dialog" onClick={()=>{setZoom(false);setGuide(false);}}><X/></button><div onClick={e=>e.stopPropagation()}>{zoom&&current?<img src={current.url} alt="Enlarged label artwork" style={{transform:`rotate(${current.rotation}deg)`}}/>:<><p className="eyebrow">HOW TO REVIEW</p><h2>A second set of eyes for your checklist</h2><ol><li>Enter the expected application values. For batches, import the JSON example with one entry per filename.</li><li>Upload each label panel as an image and select Verify. The first OCR model load can take longer; recognition time is shown for every label.</li><li>Compare any mismatch with the artwork. Missing or low-confidence text needs human review.</li><li>Check warning typography and physical dimensions, then record a reviewer decision and export the results.</li></ol><h3>Important scope</h3><p>This is a comparison prototype, not a complete TTB approval system. Wine and beer exceptions, type-specific disclosures, placement rules and ABV tolerances require an agent’s judgment. Choose whether ABV is required for the application.</p><p>OCR does not certify bold type, physical type size or difficult photos with glare and perspective distortion. Use Rotate for sideways artwork or request a clearer image.</p><p>Images, application data and decisions are held in memory on this device. Refreshing clears the workspace. Export results before closing.</p><a href={source} target="_blank" rel="noreferrer">Read the official health-warning guidance</a></>}</div></section></div>}
 </>;
}
